// player.interface.ts
export interface Player {
  idPlayer: string;
  idTeam: string;
  idTeam2: string;
  idTeamNational: string | null;
  idSoccerXML: string;
  idAPIfootball: string;
  idPlayerManager: string | null;
  idWikidata: string | null;
  strNationality: string;
  strPlayer: string;
  strPlayerAlternate: string;
  strTeam: string;
  strTeam2: string;
  strSport: string;
  intSoccerXMLTeamID: string | null;
  dateBorn: string;
  strNumber: string;
  dateSigned: string | null;
  strSigning: string;
  strWage: string;
  strOutfitter: string;
  strKit: string;
  strAgent: string;
  strBirthLocation: string;
  strEthnicity: string | null;
  strStatus: string | null;
  strDescriptionEN: string;
  strDescriptionDE: string | null;
  strDescriptionFR: string | null;
  strDescriptionCN: string | null;
  strDescriptionIT: string | null;
  strDescriptionJP: string | null;
  strDescriptionRU: string | null;
  strDescriptionES: string | null;
  strDescriptionPT: string | null;
  strDescriptionSE: string | null;
  strDescriptionNL: string | null;
  strDescriptionHU: string | null;
  strDescriptionNO: string | null;
  strDescriptionIL: string | null;
  strDescriptionPL: string | null;
  strGender: string;
  strSide: string;
  strPosition: string;
  strCollege: string | null;
  strFacebook: string;
  strWebsite: string;
  strTwitter: string;
  strInstagram: string;
  strYoutube: string;
  strHeight: string;
  strWeight: string;
  intLoved: string;
  strThumb: string;
  strCutout: string;
  strRender: string;
  strBanner: string | null;
  strFanart1: string | null;
  strFanart2: string | null;
  strFanart3: string | null;
  strFanart4: string | null;
  strCreativeCommons: string;
  strLocked: string;
}
